name: build

on: [push, pull_request]

jobs:
  build_base:
    name: Build Base DLL
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Base DLL
        run: |
          g++ -O3 -std=c++17 -fconcepts -Wall -shared -fpic src/base/*.cpp src/std/*.cpp -I include -o base.dll
          mkdir dist
          mv base.dll dist/

  build_analyzer:
    name: Build Analyzer DLL
    needs: build_base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Analyzer DLL
        run: |
          g++ -O3 -std=c++17 -fconcepts -Wall -shared -fpic src/analyzer.cpp dist/base.dll -I include -o analyzer.dll
          mv analyzer.dll dist/

  build_compiler:
    name: Build Compiler DLL
    needs: build_base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Compiler DLL
        run: |
          g++ -O3 -std=c++17 -fconcepts -Wall -shared -fpic src/compiler.cpp dist/base.dll -I include -o compiler.dll
          mv compiler.dll dist/

  build_interpreter:
    name: Build Interpreter DLL
    needs: build_base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Interpreter DLL
        run: |
          g++ -O3 -std=c++17 -fconcepts -Wall -shared -fpic src/interpreter.cpp dist/base.dll -I include -o interpreter.dll
          mv interpreter.dll dist/

  build_main:
    name: Build Main EXE
    needs: [build_analyzer, build_compiler, build_interpreter]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Main EXE
        run: |
          g++ -O3 -std=c++17 -fconcepts -Wall src/main.cpp dist/*.dll -I include -o tff.exe
